---
title: "Research"
editor: source
---

## Preprints 

-    White G.W., Wieczorek J.A., Cody Z.W., Tan E.X., Chistolini J.O., McConville K.S., Frescino T.S., and Moisen G.G. (2024+) Assessing small area estimates via bootstrap-weighted k-Nearest-Neighbor artificial populations. *arXiv preprint*. [https://arxiv.org/abs/2306.15607](https://arxiv.org/abs/2306.15607)

-   White G.W., Yamamoto J.K., Elsyad D.H., Schmitt J.F., Korsgaard N.H., Hu J.K., Gaines III G.C., Frescino T.S., and McConville K.S. (2024+) Small area estimation of forest biomass via a two-stage model for continuous zero-inflated data. *arXiv preprint*. [https://arxiv.org/abs/2402.03263](https://arxiv.org/abs/2402.03263)

## Publications

-   Emick E., Babcock C., White G.W., Hudak A.T., Domke G.M., and Finley A.O. (2023) An approach to estimating forest biomass while quantifying estimate uncertainty and correcting bias in machine learning maps. *Remote Sensing of Environment*. 295, 113678, [https://doi.org/10.1016/j.rse.2023.113678](https://doi.org/10.1016/j.rse.2023.113678)

-   Frescino T.S., Moisen G.G., Patterson P.L., Toney J.C., and White G.W. (2023) FIESTA: a forest inventory estimation and analysis R package. *Ecography*. 7, e06428, [https://doi.org/10.1111/ecog.06428](https://doi.org/10.1111/ecog.06428)

-   Frescino T.S., McConville K.S., White G.W., Toney, J.C., and Moisen G.G. (2022) Small Area Estimates for National Applications: A Database to Dashboard Strategy Using FIESTA. *Frontiers in Forests and Global Change*. 5, 107, [https://doi.org/10.3389/ffgc.2022.779446](https://doi.org/10.3389/ffgc.2022.779446)


-   White G.W., McConville K.S., Moisen G.G., and Frescino T.S. (2021) Hierarchical Bayesian Small Area Estimation Using Weakly Informative Priors in Ecologically Homogeneous Areas of the Interior Western Forests. *Frontiers in Forests and Global Change*. 4, 178, [https://doi.org/10.3389/ffgc.2021.752911](https://doi.org/10.3389/ffgc.2021.752911)

## Software 

-   Grayson W. White, Hannah Frick, and Simon Couch (2024). forested: Forest Attributes in Washington State. R package version 0.1.0. [https://CRAN.R-project.org/package=forested](https://CRAN.R-project.org/package=forested)

-   Grayson W. White, Jerzy A. Wieczorek, Tracey S. Frescino, and Kelly S. McConville (2024). kbaabb: A kNN-based approximation to the approximate Bayesian bootstrap. R package version 0.0.0.9000. [https://github.com/graysonwhite/kbaabb/](https://github.com/graysonwhite/kbaabb/)

-   Tracey S. Frescino, Gretchen G. Moisen, Paul L. Patterson, J. Chris Toney, and Grayson W. White (2022). FIESTA: A forest inventory estimation and analysis R package. R package version 3.6.4. [https://cran.r-project.org/package=FIESTA](https://cran.r-project.org/package=FIESTA)

-   Grayson W. White (2020). gglm: Grammar of Graphics for Linear Model Diagnostics. R package version 1.0.2. [https://CRAN.R-project.org/package=gglm](https://CRAN.R-project.org/package=gglm)