---
title: "Teaching"
editor: source
---

As an educator I aim to create an inclusive, safe, welcoming, and productive space for students to engage deeply with statistics and data science concepts. I strive to help students gain confidence in their mathematical, statistical, and programmatic skills by making my courses feel accessible and welcoming, genuinely engaging with questions and feedback from students, and adapting my practices based on continued experience in the classroom. 

## Courses

### At Reed College

- Instructor, Stat 243: Statistical Learning ([Fall 2026](https://stat-243-f26.github.io/))

- Instructor, Stat/Math 241: Data Science ([Fall 2026](https://stat-241-f26.github.io/), [Spring 2026](https://reed-data-science.github.io/))

- Instructor, Math 141: Introduction to Probability and Statistics ([Fall 2025]((https://math-141.github.io/)))

### At Michigan State University

- Instructor, Forestry 128: Practical Computing and Data Science Tools ([Fall 2024]((http://www.for128.org)))

- Teaching Assistant, Forestry 372: Ecological Monitoring and Data Analysis (Spring 2023, Spring 2024)

- Teaching Assistant, Forestry 128: Practical Computing and Data Science Tools (Spring 2023)

## Other experience 

Prior to my time in academia, I was a Data Science Educator at [Posit](http://www.posit.co). Further, as an undergraduate at Reed College I was a Course Assistant and Tutor for Math 141: Introduction to Probability and Statistics, Math 241: Data Science, Math 392: Mathematical Statistics, and Econ 311: Survey of Econometric Methods.
